Algoritmo "Questão 9"
// Faça um programa que pergunte a idade da pessoa
// em anos,meses e dias e depois mostre os dias
Var
// Seção de Declarações das variáveis 
anos,meses,dias,days,total: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
anos <- 365
meses <- 30
days <- anos+meses+dias

Escreval("Coloque sua idade em anos,meses e em dias")
leia(total)

escreval("Aqui está a sua idade em dias", days)



Fimalgoritmo