Algoritmo "Questão 2"
// Criar um programa que pergunte
//Horas e minutos separadamente e logo após
//Fale quanto tempo já se passou da meia noite
Var
// Seção de Declarações das variáveis 
hr,min,finim: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Quantas horas são: ")
leia(hr)

escreval("Quantos minutos tem: ")
leia(min)

finim<- (60*hr) + min
escreval("A minutagem passada dês da 00:00 é: ", finim)



Fimalgoritmo