Algoritmo "Questão 7"
//  Faça um algoritimo que pergunte o
// valor da prestação e o número de prestações
// depois apresente o valor total
Var
// Seção de Declarações das variáveis 
pre,va,paia: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Informe o valor das perstações: ")
leia(va)

escreval("Quantas pretações há? ")
leia(paia)

pre <- va * paia
Escreval("Aqui está o valor final do produto", pre)


Fimalgoritmo